[package]
name = "paycube"
version = "0.1.0"
authors = ["Christian Nyumbayire"]
edition = "2018"

license-file = "LICENSE.md"

[dependencies]
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
typenum = "^1"
arraystring = { version = "^0.3", features = ["std", "serde-traits"] }
